#!/usr/bin/env python3
"""
extract_overlay.py — carve AC1 FDAT.T *code overlays* for static analysis.

Background: docs/MXT_LOADER.md. FDAT.T (the MXT archive, mxtid 2) stores the
game's runtime code overlays as ordinary container entries. They are loaded by
mxt_load_entry (FUN_800165e4) to a FIXED RAM base with NO relocation, so a raw
entry payload IS the runtime memory image (minus its trailing checksum word).
That's why the in-mission code is absent from the Ghidra DB: the DB only ever
captured the entry-201 (front-end) build of the shared overlay region; every
other overlay loads to the same addresses and was never imported.

Overlay set (all load to base 0x8004ada0 = PTR_DAT_800112c8):
  201 (0xc9)  front_end   front-end / garage-menu  (== the Ghidra DB overlay build)
  202 (0xca)  mission     in-mission runtime       (mode DAT_80039c5e == 0)
  203 (0xcb)  mode1       mode overlay             (mode == 1)
  204 (0xcc)  mode2       mode overlay             (mode == 2)

Container TOC convention: FDAT.T is "count-first" (u16[0]=entry count, offsets
start at u16[1]); so on-disc offset[i] = u16[1+i], entry i spans sectors
offset[i]..offset[i+1], 2048 B/sector. (The live mxt_head_work copy at 0x800435da
drops the count word, hence its index is one lower than the file's.)

Source: fdat_extracted.T (de-sectored flat container) by default. Use --disc to
read sectors straight from the Mode2/2352 .bin via tools/extract_t.read_sectors.

For each entry it verifies the MXT trailing checksum (seed 0x12345678 + sum of
all-but-last words == last word), writes <name>.bin, and (optionally) emits a
Ghidra import script that drops the image into an overlay block at 0x8004ada0.

CLI:
  python3 tools/extract_overlay.py                 # carve 201..204 + verify + ghidra scripts
  python3 tools/extract_overlay.py --entry 202     # just one
  python3 tools/extract_overlay.py --disc          # carve from the pristine .bin instead
  python3 tools/extract_overlay.py --no-ghidra     # skip script emission
"""
import sys, os, json, struct, argparse

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_SIZE = 2048
WORDS_PER_SECTOR = DATA_SIZE // 4          # 512
CHECKSUM_SEED = 0x12345678
LOAD_BASE = 0x8004ada0                     # PTR_DAT_800112c8 — overlay load address

# entry -> (short_name, description, mode_selector)
OVERLAYS = {
    201: ("front_end", "front-end / garage-menu (Ghidra DB overlay build)", None),
    202: ("mission",   "in-mission runtime",                  0),
    203: ("mode1",     "mode overlay (DAT_80039c5e==1)",      1),
    204: ("mode2",     "mode overlay (DAT_80039c5e==2)",      2),
}


def read_toc(container: bytes):
    """Return (count, offsets[]) for the count-first FDAT.T TOC. offsets[i] is the
    file-relative start sector of entry i; offsets has count+1 entries (last =
    end sentinel)."""
    u = struct.unpack_from("<1024H", container, 0)
    count = u[0]
    offsets = list(u[1:1 + count + 1])     # offset[0..count]
    return count, offsets


def verify_checksum(payload: bytes):
    """MXT checksum (FUN_80015b24): sum all words except the last, seeded; the
    last word is the stored checksum. Returns (ok, computed, stored)."""
    nwords = len(payload) // 4
    words = struct.unpack_from(f"<{nwords}I", payload, 0)
    s = CHECKSUM_SEED
    for w in words[:-1]:
        s = (s + w) & 0xFFFFFFFF
    return (s == words[-1]), s, words[-1]


def load_container(disc: bool):
    if disc:
        # read FDAT.T sectors straight from the pristine Mode2/2352 .bin
        sys.path.insert(0, os.path.join(HERE, "tools"))
        import extract_t
        fm = json.load(open(os.path.join(HERE, "disc_map", "disc_files.json")))
        rec = next(r for r in fm["files"] if r.get("path", "").endswith("FDAT.T"))
        first, last = rec["sector_first"], rec["sector_last"]
        print(f"[disc] FDAT.T sectors {first}-{last} from {os.path.basename(fm['source_bin'])}")
        return extract_t.read_sectors(fm["source_bin"], first, last - first + 1)
    path = os.path.join(HERE, "fdat_extracted.T")
    print(f"[flat] {path}")
    return open(path, "rb").read()


def ghidra_script(entry: int, name: str, bin_path: str) -> str:
    """Emit a Ghidra (Jython) script that imports the overlay into the CURRENT
    program as an overlay memory block at LOAD_BASE and disassembles it."""
    return f'''# import_ovl_{entry}_{name}.py  (auto-generated by tools/extract_overlay.py)
# Ghidra script: load FDAT.T entry {entry} ({name}) as an overlay block at
# 0x{LOAD_BASE:08x} in the current program, so calls into resident code resolve
# while the mission build occupies its real addresses in a separate overlay space.
#
# Run from Ghidra's Script Manager against the AC_1_USA_RE program. The overlay
# region (0x{LOAD_BASE:08x}..) already holds the entry-201 build; an OVERLAY block
# gives this entry its own address space without clobbering that.
#@category AC1
import jarray
from ghidra.program.model.mem import MemoryConflictHandler

BIN = r"{bin_path}"
BASE = 0x{LOAD_BASE:08x}
NAME = "ovl{entry}_{name}"

data = open(BIN, "rb").read()
mem = currentProgram.getMemory()
addr = currentProgram.getAddressFactory().getDefaultAddressSpace().getAddress(BASE)
blk = mem.createInitializedBlock(NAME, addr, len(data), (0).to_bytes(1,'little')[0] if False else 0,
                                 monitor, True)  # overlay=True
ov_addr = blk.getStart()
mem.setBytes(ov_addr, jarray.array(data, 'b'))
print("created overlay block %s at %s (len %d)" % (NAME, ov_addr, len(data)))
# disassemble the whole block
from ghidra.app.cmd.disassemble import DisassembleCommand
from ghidra.program.model.address import AddressSet
DisassembleCommand(AddressSet(blk.getStart(), blk.getEnd()), None, True).applyTo(currentProgram, monitor)
print("disassembled; run Auto-Analyze for full xrefs.")
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--entry", type=int, action="append",
                    help="entry index to carve (repeatable); default = 201,202,203,204")
    ap.add_argument("--disc", action="store_true", help="carve from pristine .bin not fdat_extracted.T")
    ap.add_argument("--out", default=os.path.join(HERE, "disc_map", "overlays"))
    ap.add_argument("--no-ghidra", action="store_true", help="don't emit Ghidra import scripts")
    ap.add_argument("--verify", help="compare carved entry to this reference .bin")
    args = ap.parse_args()

    entries = args.entry or [201, 202, 203, 204]
    os.makedirs(args.out, exist_ok=True)
    gdir = os.path.join(HERE, "ghidra_scripts")

    container = load_container(args.disc)
    total_sectors = len(container) // DATA_SIZE
    count, offsets = read_toc(container)
    print(f"FDAT.T: {count} entries, {total_sectors} sectors, {len(container):,} B; "
          f"load base 0x{LOAD_BASE:08x}\n")

    manifest = []
    for e in entries:
        if e + 1 >= len(offsets):
            print(f"  entry {e}: out of range"); continue
        s0, s1 = offsets[e], offsets[e + 1]
        byte_off, byte_len = s0 * DATA_SIZE, (s1 - s0) * DATA_SIZE
        payload = container[byte_off:byte_off + byte_len]
        ok, comp, stored = verify_checksum(payload) if byte_len else (None, 0, 0)
        name, desc, mode = OVERLAYS.get(e, (f"entry{e}", "?", None))
        end_addr = LOAD_BASE + byte_len
        out_bin = os.path.join(args.out, f"ovl{e}_{name}.bin")
        with open(out_bin, "wb") as f:
            f.write(payload)
        cks = "n/a" if ok is None else (f"OK (0x{stored:08x})" if ok
                                        else f"MISMATCH comp=0x{comp:08x} stored=0x{stored:08x}")
        print(f"  entry {e} [{name}] sectors {s0}..{s1} ({s1-s0} sec, {byte_len:,} B)")
        print(f"      RAM 0x{LOAD_BASE:08x}..0x{end_addr:08x}   checksum {cks}")
        print(f"      -> {out_bin}")
        rec = {"entry": e, "name": name, "desc": desc, "mode_selector": mode,
               "sector_start": s0, "sector_count": s1 - s0, "byte_len": byte_len,
               "load_base": LOAD_BASE, "ram_end": end_addr,
               "checksum_ok": ok, "checksum": stored, "bin": os.path.relpath(out_bin, HERE)}

        if args.verify and e == entries[0]:
            ref = open(args.verify, "rb").read()
            rec["verify_ref"] = args.verify
            rec["verify_match"] = (ref == payload)
            if ref == payload:
                print(f"      verify: EXACT match vs {os.path.basename(args.verify)}")
            else:
                n = min(len(ref), len(payload))
                fd = next((i for i in range(n) if ref[i] != payload[i]), n)
                same = sum(1 for i in range(n) if ref[i] == payload[i])
                print(f"      verify: differs vs {os.path.basename(args.verify)} "
                      f"(len {len(ref)} vs {len(payload)}; first diff @0x{fd:x}; "
                      f"{same}/{n} bytes equal = {100*same/n:.2f}%)")

        if not args.no_ghidra:
            os.makedirs(gdir, exist_ok=True)
            gpath = os.path.join(gdir, f"import_ovl_{e}_{name}.py")
            with open(gpath, "w") as f:
                f.write(ghidra_script(e, name, out_bin))
            rec["ghidra_script"] = os.path.relpath(gpath, HERE)
            print(f"      ghidra: {gpath}")
        manifest.append(rec)
        print()

    man_path = os.path.join(args.out, "overlays.json")
    json.dump({"load_base": LOAD_BASE, "source": "disc" if args.disc else "fdat_extracted.T",
               "overlays": manifest}, open(man_path, "w"), indent=1)
    print(f"manifest -> {man_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
