# import_ovl_203_mode1.py  (auto-generated by tools/extract_overlay.py)
# Ghidra script: load FDAT.T entry 203 (mode1) as an overlay block at
# 0x8004ada0 in the current program, so calls into resident code resolve
# while the mission build occupies its real addresses in a separate overlay space.
#
# Run from Ghidra's Script Manager against the AC_1_USA_RE program. The overlay
# region (0x8004ada0..) already holds the entry-201 build; an OVERLAY block
# gives this entry its own address space without clobbering that.
#@category AC1
import jarray
from ghidra.program.model.mem import MemoryConflictHandler

BIN = r"/home/byron/Desktop/AC_1_USA_RE/disc_map/overlays/ovl203_mode1.bin"
BASE = 0x8004ada0
NAME = "ovl203_mode1"

data = open(BIN, "rb").read()
mem = currentProgram.getMemory()
addr = currentProgram.getAddressFactory().getDefaultAddressSpace().getAddress(BASE)
blk = mem.createInitializedBlock(NAME, addr, len(data), (0).to_bytes(1,'little')[0] if False else 0,
                                 monitor, True)  # overlay=True
ov_addr = blk.getStart()
mem.setBytes(ov_addr, jarray.array(data, 'b'))
print("created overlay block %s at %s (len %d)" % (NAME, ov_addr, len(data)))
# disassemble the whole block
from ghidra.app.cmd.disassemble import DisassembleCommand
from ghidra.program.model.address import AddressSet
DisassembleCommand(AddressSet(blk.getStart(), blk.getEnd()), None, True).applyTo(currentProgram, monitor)
print("disassembled; run Auto-Analyze for full xrefs.")
